export const ANNOUNCEMENTS = {
  FETCH_ANNOUNCEMENTS: 'ANNOUNCEMENTS/FETCH_ANNOUNCEMENTS',
  FETCH_ANNOUNCEMENTS_SUCCESS: 'ANNOUNCEMENTS/FETCH_ANNOUNCEMENTS_SUCCESS',

  FETCH_ANNOUNCEMENT: 'ANNOUNCEMENTS/FETCH_ANNOUNCEMENT',
  FETCH_ANNOUNCEMENT_SUCCESS: 'ANNOUNCEMENTS/FETCH_ANNOUNCEMENT_SUCCESS',

  CREATE_ANNOUNCEMENT: 'ANNOUNCEMENTS/CREATE_ANNOUNCEMENT',
  CREATE_ANNOUNCEMENT_SUCCESS: 'ANNOUNCEMENTS/CREATE_ANNOUNCEMENT_SUCCESS'
};
