export const ARCHIVE = {
  FETCH_ARCHIVES: 'ARCHIVES/FETCH_ARCHIVES',
  FETCH_ARCHIVES_SUCCESS: 'ARCHIVES/FETCH_ARCHIVES_SUCCESS',

  ARCHIVE: 'ARCHIVE/ARCHIVE',
  ARCHIVE_SUCCESS: 'ARCHIVE/ARCHIVE_SUCCESS'
};
