export const AUTH = {
  LOGIN: 'AUTH/LOGIN',
  SET_CURRENT_USER: 'AUTH/SET_CURRENT_USER',
  LOGOUT: 'AUTH/LOGOUT',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  SET_COLOR_THEME: 'USERS/SET_COLOR_THEME'
};
