export const COLLEGES = {
  FETCH_COLLEGES: 'EVENTS/FETCH_COLLEGES',
  FETCH_COLLEGES_SUCCESS: 'EVENTS/FETCH_COLLEGES_SUCCESS',

  ADD_COLLEGE: 'EVENTS/ADD_COLLEGE',
  ADD_COLLEGE_SUCCESS: 'EVENTS/ADD_COLLEGE_SUCCESS'
};
