export const COURSES = {
  FETCH_COURSES: 'EVENTS/FETCH_COURSES',
  FETCH_COURSES_SUCCESS: 'EVENTS/FETCH_COURSES_SUCCESS',

  ADD_COURSE: 'EVENTS/ADD_COURSE',
  ADD_COURSE_SUCCESS: 'EVENTS/ADD_COURSE_SUCCESS'
};
