export const EDIT = {
  FETCH_EDIT: 'EDIT/FETCH_EDIT',
  FETCH_EDIT_SUCCESS: 'EDIT/FETCH_EDIT_SUCCESS',

  SAVE_EDIT: 'EDIT/SAVE_EDIT',
  SAVE_EDIT_SUCCESS: 'EDIT/SAVE_EDIT_SUCCESS',

  EDIT_MODAL_CLOSE: 'EDIT/EDIT_MODAL_CLOSE'
};
