export const EMAILS = {
  FETCH_EMAILS: 'EMAILS/FETCH_EMAILS',
  FETCH_EMAILS_SUCCESS: 'EMAIL/FETCH_EMAILS_SUCCESS',

  FETCH_EMAIL: 'EMAILS/FETCH_EMAIL',
  FETCH_EMAIL_SUCCESS: 'EMAIL/FETCH_EMAIL_SUCCESS',

  CREATE_EMAIL: 'EMAILS/CREATE_EMAIL',
  CREATE_EMAIL_SUCCESS: 'EMAILS/CREATE_EMAIL_SUCCESS',

  SEND_CERTIFICATE: 'EMAILS/SEND_CERTIFICATE',
  SEND_CERTIFICATE_SUCCESS: 'EMAILS/SEND_CERTIFICATE_SUCCESS'
};
