export const EVENTS = {
  FETCH_EVENTS: 'EVENTS/FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS: 'EVENTS/FETCH_EVENTS_SUCCESS',

  CREATE_EVENT: 'EVENTS/CREATE_EVENT',
  CREATE_EVENT_SUCCESS: 'EVENTS/CREATE_EVENT_SUCCESS'
};
