export const EVENTS = {
  FETCH_EVENTS: 'EVENTS/FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS: 'EVENTS/FETCH_EVENTS_SUCCESS',

  FETCH_EVENT: 'EVENTS/FETCH_EVENT',
  FETCH_EVENT_SUCCESS: 'EVENTS/FETCH_EVENT_SUCCESS',

  CREATE_EVENT: 'EVENTS/CREATE_EVENT',
  CREATE_EVENT_SUCCESS: 'EVENTS/CREATE_EVENT_SUCCESS',

  REGISTER: 'EVENTS/REGISTER',
  REGISTER_SUCCESS: 'EVENTS/REGISTER_SUCCESS'
};
