export const EVENTS = {
  FETCH_EVENTS: 'EVENTS/FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS: 'EVENTS/FETCH_EVENTS_SUCCESS',

  FETCH_EVENT: 'EVENTS/FETCH_EVENT',
  FETCH_EVENT_SUCCESS: 'EVENTS/FETCH_EVENT_SUCCESS',

  CREATE_EVENT: 'EVENTS/CREATE_EVENT',
  CREATE_EVENT_SUCCESS: 'EVENTS/CREATE_EVENT_SUCCESS',

  REGISTER: 'EVENTS/REGISTER',
  REGISTER_SUCCESS: 'EVENTS/REGISTER_SUCCESS',

  FETCH_ATTENDEE: 'EVENTS/FETCH_ATTENDEE',
  FETCH_ATTENDEE_SUCCESS: 'EVENTS/FETCH_ATTENDEE_SUCCESS',

  FETCH_ATTENDEES: 'EVENTS/FETCH_ATTENDEES',
  FETCH_ATTENDEES_SUCCESS: 'EVENTS/FETCH_ATTENDEES_SUCCESS',

  ATTEND: 'EVENTS/ATTEND',
  ATTEND_SUCCESS: 'EVENTS/ATTEND_SUCCESS',

  SETTLE_PAYMENT: 'EVENTS/SETTLE_PAYMENT',
  SETTLE_PAYMENT_SUCCESS: 'EVENTS/SETTLE_PAYMENT_SUCCESS',

  REGISTER_IMPORTS: 'EVENTS/REGISTER_IMPORTS',
  REGISTER_IMPORTS_SUCCESS: 'EVENTS/REGISTER_IMPORTS_SUCCESS'
};
