export const ORGANIZATIONS = {
  FETCH_ORGANIZATIONS: 'ORGANIZATIONS/FETCH_ORGANIZATIONS',
  FETCH_ORGANIZATIONS_SUCCESS: 'ORGANIZATIONS/FETCH_ORGANIZATIONS_SUCCESS',
  FETCH_ORGANIZATION: 'ORGANIZATIONS/FETCH_ORGANIZATION',
  FETCH_ORGANIZATION_SUCCESS: 'ORGANIZATIONS/FETCH_ORGANIZATION_SUCCESS',
  ADD_ORGANIZATION: 'ORGANIZATIONS/ADD_ORGANIZATION',
  ADD_ORGANIZATION_SUCCESS: 'ORGANIZATIONS/ADD_ORGANIZATION_SUCCESS',
  ADD_ORGANIZATION_USER: 'ORGANIZATIONS/ADD_ORGANIZATION_USER',
  ADD_ORGANIZATION_USER_SUCCESS: 'ORGANIZATIONS/ADD_ORGANIZATION_USER_SUCCESS'
};
