export const ORGANIZATIONS = {
  FETCH_ORGANIZATIONS: 'ORGANIZATIONS/FETCH_ORGANIZATIONS',
  FETCH_ORGANIZATIONS_SUCCESS: 'ORGANIZATIONS/FETCH_ORGANIZATIONS_SUCCESS',
  FETCH_ORGANIZATION: 'ORGANIZATIONS/FETCH_ORGANIZATION',
  FETCH_ORGANIZATION_SUCCESS: 'ORGANIZATIONS/FETCH_ORGANIZATION_SUCCESS',
  FETCH_CURRENT_ORGANIZATION: 'ORGANIZATIONS/FETCH_CURRENT_ORGANIZATION',
  FETCH_CURRENT_ORGANIZATION_SUCCESS: 'ORGANIZATIONS/FETCH_CURRENT_ORGANIZATION_SUCCESS',
  ADD_ORGANIZATION: 'ORGANIZATIONS/ADD_ORGANIZATION',
  ADD_ORGANIZATION_SUCCESS: 'ORGANIZATIONS/ADD_ORGANIZATION_SUCCESS',

  FETCH_ORGANIZATION_TO_USER_SIDE: 'ORGANIZATIONS/FETCH_ORGANIZATION_TO_USER_SIDE',
  FETCH_ORGANIZATION_TO_USER_SIDE_SUCCESS: 'ORGANIZATIONS/FETCH_ORGANIZATION_TO_USER_SIDE_SUCCESS'
};
