export const RENEWAL = {
  SET_RENEWAL: 'RENEWAL/SET_RENEWAL',
  SET_RENEWAL_SUCCESS: 'RENEWAL/SET_RENEWAL_SUCCESS',

  GET_RENEWAL: 'RENEWAL/GET_RENEWAL',
  GET_RENEWAL_SUCCESS: 'RENEWAL/GET_RENEWAL_SUCCESS'
};
