export const SHIRTS = {
  FETCH_SHIRT: 'SHIRTS/FETCH_SHIRT',
  FETCH_SHIRT_SUCCESS: 'SHIRTS/FETCH_SHIRT_SUCCESS',

  FETCH_SHIRT_ORGANIZATION: 'SHIRTS/FETCH_SHIRT_ORGANIZATION',
  FETCH_SHIRT_ORGANIZATION_SUCCESS: 'SHIRTS/FETCH_SHIRT_ORGANIZATION_SUCCESS',

  ADD_ORGSHIRT: 'SHIRTS/ADD_ORGSHIRT',
  ADD_ORGSHIRT_SUCCESS: 'SHIRTS/ADD_ORGSHIRT_SUCCESS',

  FETCH_SIZES: 'SHIRTS/FETCH_SIZES',
  FETCH_SIZES_SUCCESS: 'SHIRTS/FETCH_SIZES_SUCCESS',

  PURCHASE_SHIRT: 'SHIRTS/PURCHASE_SHIRT',
  PURCHASE_SHIRT_SUCCESS: 'SHIRTS/PURCHASE_SHIRT_SUCCESS',

  FETCH_PURCHASE_SHIRTS: 'SHIRTS/FETCH_PURCHASE_SHIRTS',
  FETCH_PURCHASE_SHIRTS_SUCCESS: 'SHIRTS/FETCH_PURCHASE_SHIRTS_SUCCESS',

  PURCHASE_IMPORTS: 'SHIRTS/PURCHASE_IMPORTS',
  PURCHASE_IMPORTS_SUCCESS: 'SHIRTS/PURCHASE_IMPORTS_SUCCESS'
};
