export const SHIRTS = {
  FETCH_SHIRTS: 'SHIRTS/FETCH_SHIRTS',
  FETCH_SHIRTS_SUCCESS: 'SHIRTS/FETCH_SHIRTS_SUCCESS',

  VERIFY_MEMBER: 'SHIRTS/VERIFY_MEMBER',
  VERIFY_MEMBER_SUCCESS: 'SHIRTS/VERIFY_MEMBER_SUCCESS',

  ADD_ORGSHIRT: 'SHIRTS/ADD_ORGSHIRT',
  ADD_ORGSHIRT_SUCCESS: 'SHIRTS/ADD_ORGSHIRT_SUCCESS',

  FETCH_SIZES: 'SHIRTS/FETCH_SIZES',
  FETCH_SIZES_SUCCESS: 'SHIRTS/FETCH_SIZES_SUCCESS',

  PURCHASE_SHIRT: 'SHIRTS/PURCHASE_SHIRT',
  PURCHASE_SHIRT_SUCCESS: 'SHIRTS/PURCHASE_SHIRT_SUCCESS'
};
