export const SHIRTS = {
  FETCH_SHIRTS: 'SHIRTS/FETCH_SHIRTS',
  FETCH_SHIRTS_SUCCESS: 'SHIRTS/FETCH_SHIRTS_SUCCESS',
  VERIFY_MEMBER: 'SHIRTS/VERIFY_MEMBER',
  VERIFY_MEMBER_SUCCESS: 'SHIRTS/VERIFY_MEMBER_SUCCESS'
};
