export const SMSS = {
  FETCH_SMSS: 'SMSS/FETCH_SMSS',
  FETCH_SMSS_SUCCESS: 'SMS/FETCH_SMSS_SUCCESS',

  FETCH_SMS: 'SMSS/FETCH_SMS',
  FETCH_SMS_SUCCESS: 'SMS/FETCH_SMS_SUCCESS',

  CREATE_SMS: 'SMSS/CREATE_SMS',
  CREATE_SMS_SUCCESS: 'SMSS/CREATE_SMS_SUCCESS'
};
