export const USERS = {
  FETCH_USERS: 'USERS/FETCH_USERS',
  FETCH_USERS_SUCCESS: 'USERS/FETCH_USERS_SUCCESS',
  FETCH_PRESIDENTS: 'USERS/FETCH_PRESIDENTS',
  FETCH_PRESIDENTS_SUCCESS: 'USERS/FETCH_PRESIDENTS_SUCCESS',
  FETCH_MEMBERS: 'USERS/FETCH_MEMBERS',
  FETCH_MEMBERS_SUCCESS: 'USERS/FETCH_MEMBERS_SUCCESS',

  ADD_MEMBER: 'USERS/ADD_MEMBER',
  ADD_MEMBER_SUCCESS: 'USERS/ADD_MEMBER_SUCCESS',

  ADD_USER: 'USERS/ADD_USER',
  ADD_USER_SUCCESS: 'USERS/ADD_USER_SUCCESS',

  VERIFY_MEMBER: 'USERS/VERIFY_MEMBER',
  VERIFY_MEMBER_SUCCESS: 'USERS/VERIFY_MEMBER_SUCCESS',

  ADD_MEMBERS: 'USERS/ADD_MEMBERS',
  ADD_MEMBERS_SUCCESS: 'USERS/ADD_MEMBERS_SUCCESS'
};
