export const USERS = {
  FETCH_USERS: 'USERS/FETCH_USERS',
  FETCH_USERS_SUCCESS: 'USERS/FETCH_USERS_SUCCESS',
  FETCH_PRESIDENTS: 'USERS/FETCH_PRESIDENTS',
  FETCH_PRESIDENTS_SUCCESS: 'USERS/FETCH_PRESIDENTS_SUCCESS',
  FETCH_MEMBERS: 'USERS/FETCH_MEMBERS',
  FETCH_MEMBERS_SUCCESS: 'USERS/FETCH_MEMBERS_SUCCESS',

  ADD_MEMBER: 'USERS/ADD_MEMBER',
  ADD_MEMBER_SUCCESS: 'USERS/ADD_MEMBER_SUCCESS'
};
