export const USERS = {
  FETCH_USERS: 'USERS/FETCH_USERS',
  FETCH_USERS_SUCCESS: 'USERS/FETCH_USERS_SUCCESS',
  FETCH_PRESIDENTS: 'PRESIDENTS/FETCH_PRESIDENTS',
  FETCH_PRESIDENTS_SUCCESS: 'PRESIDENTS/FETCH_PRESIDENTS_SUCCESS'
};
